<a href="https://colab.research.google.com/github/drago467/AIVN-MODULE-1/blob/main/6_CustomClass_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Sigmoid

In [ ]:
import torch
import torch.nn as nn

sigmoid_function = nn.Sigmoid()
data = torch.Tensor([1, 2, 3])
output = sigmoid_function(data)
print(output)

tensor([0.7311, 0.8808, 0.9526])


In [ ]:
class MySigmoid(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return 1 / (1 + torch.exp(-x))

In [ ]:
my_sigmoid = MySigmoid()
output = my_sigmoid(data)
print(output)

tensor([0.7311, 0.8808, 0.9526])


## Relu

In [ ]:
import torch
import torch.nn as nn

class MyReluActivation(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x):
        zeros = torch.zeros_like(x)
        return torch.maximum(x, zeros)

In [ ]:
data = torch.Tensor([1, -2, 3])
my_relu = MyReluActivation()
output = my_relu(data)
print(output)

tensor([1., 0., 3.])


In [ ]:
import torch
import torch.nn as nn

softmax = nn.Softmax()
data = torch.Tensor([1, 2, 3])
output = softmax(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])


e:\SoftInstallation\conda\envs\torch_env\Lib\site-packages\torch\nn\modules\module.py:1511: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)


In [ ]:
class MySoftmaxActivation(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_exp = torch.exp(x)
        return x_exp/torch.sum(x_exp)

# test
softmax = MySoftmaxActivation()
data = torch.Tensor([1, 2, 3])
output = softmax(data)
print(output)

tensor([0.0900, 0.2447, 0.6652])


In [ ]:
data = torch.Tensor([1, 2, 3])
torch.exp(data)


tensor([ 2.7183,  7.3891, 20.0855])

In [ ]:
torch.sum(torch.exp(data))

tensor(30.1929)